-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 20:20:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vms` ;

-- -----------------------------------------------------
-- Schema vms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vms` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `vms` ;

-- -----------------------------------------------------
-- Table `vms`.`all_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`all_roles` ;

CREATE TABLE IF NOT EXISTS `vms`.`all_roles` (
  `role_code` VARCHAR(10) NOT NULL,
  `role_description` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`role_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`images` ;

CREATE TABLE IF NOT EXISTS `vms`.`images` (
  `image_id` INT(11) NOT NULL,
  `image_data` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`employee` ;

CREATE TABLE IF NOT EXISTS `vms`.`employee` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(20) NULL DEFAULT NULL,
  `photo` INT(11) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `employee_images_photo` (`photo` ASC) VISIBLE,
  CONSTRAINT `employee_images_photo`
    FOREIGN KEY (`photo`)
    REFERENCES `vms`.`images` (`image_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`employee_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`employee_role` ;

CREATE TABLE IF NOT EXISTS `vms`.`employee_role` (
  `emp_id` INT(10) NULL DEFAULT NULL,
  `role_code` VARCHAR(10) NULL DEFAULT NULL,
  INDEX `employee_role_employee_emp_id` (`emp_id` ASC) VISIBLE,
  INDEX `employee_role_all_roles_role_code` (`role_code` ASC) VISIBLE,
  CONSTRAINT `employee_role_all_roles_role_code`
    FOREIGN KEY (`role_code`)
    REFERENCES `vms`.`all_roles` (`role_code`),
  CONSTRAINT `employee_role_employee_emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `vms`.`employee` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`security_locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`security_locations` ;

CREATE TABLE IF NOT EXISTS `vms`.`security_locations` (
  `location_code` INT(6) NOT NULL,
  `description` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`location_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`security`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`security` ;

CREATE TABLE IF NOT EXISTS `vms`.`security` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `location_id` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `security_security_locations_location_id` (`location_id` ASC) VISIBLE,
  CONSTRAINT `security_security_locations_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `vms`.`security_locations` (`location_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`security_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`security_role` ;

CREATE TABLE IF NOT EXISTS `vms`.`security_role` (
  `security_id` INT(10) NULL DEFAULT NULL,
  `role_code` VARCHAR(10) NULL DEFAULT NULL,
  INDEX `security_role_security_security_id` (`security_id` ASC) VISIBLE,
  INDEX `security_role_all_roles_role_code` (`role_code` ASC) VISIBLE,
  CONSTRAINT `security_role_all_roles_role_code`
    FOREIGN KEY (`role_code`)
    REFERENCES `vms`.`all_roles` (`role_code`),
  CONSTRAINT `security_role_security_security_id`
    FOREIGN KEY (`security_id`)
    REFERENCES `vms`.`security` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`visitor_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`visitor_status` ;

CREATE TABLE IF NOT EXISTS `vms`.`visitor_status` (
  `status_code` INT(2) NOT NULL,
  `description` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`status_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`visitor_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`visitor_type` ;

CREATE TABLE IF NOT EXISTS `vms`.`visitor_type` (
  `visitor_type_cd` VARCHAR(10) NOT NULL,
  `visitor_type_desc` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`visitor_type_cd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`visitor` ;

CREATE TABLE IF NOT EXISTS `vms`.`visitor` (
  `id` INT(10) NOT NULL,
  `visitor_type_cd` VARCHAR(10) NULL DEFAULT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(20) NULL DEFAULT NULL,
  `uploaded_photo` INT(11) NULL DEFAULT NULL,
  `actual_photo` INT(11) NULL DEFAULT NULL,
  `refered_by` INT(10) NULL DEFAULT NULL,
  `expected_in_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `actual_in_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `expected_out_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `actual_out_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `status` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `visitor_visitor_type_visitor_type_cd` (`visitor_type_cd` ASC) VISIBLE,
  INDEX `visitor_images_uploaded_photo` (`uploaded_photo` ASC) VISIBLE,
  INDEX `visitor_images_actual_photo` (`actual_photo` ASC) VISIBLE,
  INDEX `visitor_employee_refered_by` (`refered_by` ASC) VISIBLE,
  INDEX `visitor_visitor_status_status` (`status` ASC) VISIBLE,
  CONSTRAINT `visitor_employee_refered_by`
    FOREIGN KEY (`refered_by`)
    REFERENCES `vms`.`employee` (`id`),
  CONSTRAINT `visitor_images_actual_photo`
    FOREIGN KEY (`actual_photo`)
    REFERENCES `vms`.`images` (`image_id`),
  CONSTRAINT `visitor_images_uploaded_photo`
    FOREIGN KEY (`uploaded_photo`)
    REFERENCES `vms`.`images` (`image_id`),
  CONSTRAINT `visitor_visitor_status_status`
    FOREIGN KEY (`status`)
    REFERENCES `vms`.`visitor_status` (`status_code`),
  CONSTRAINT `visitor_visitor_type_visitor_type_cd`
    FOREIGN KEY (`visitor_type_cd`)
    REFERENCES `vms`.`visitor_type` (`visitor_type_cd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`visitor_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`visitor_access` ;

CREATE TABLE IF NOT EXISTS `vms`.`visitor_access` (
  `visitor_type_cd` VARCHAR(10) NOT NULL,
  `location_code` INT(6) NULL,
  INDEX `visitor_access_visitor_type_visitor_type_cd` (`visitor_type_cd` ASC) VISIBLE,
  INDEX `fk_visitor_access_security_locations1_idx` (`location_code` ASC) VISIBLE,
  CONSTRAINT `visitor_access_visitor_type_visitor_type_cd`
    FOREIGN KEY (`visitor_type_cd`)
    REFERENCES `vms`.`visitor_type` (`visitor_type_cd`),
  CONSTRAINT `fk_visitor_access_security_locations1`
    FOREIGN KEY (`location_code`)
    REFERENCES `vms`.`security_locations` (`location_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`event_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`event_codes` ;

CREATE TABLE IF NOT EXISTS `vms`.`event_codes` (
  `event_type` INT(2) NOT NULL,
  `event_name` VARCHAR(45) NULL,
  PRIMARY KEY (`event_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vms`.`visitor_movement_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`visitor_movement_log` ;

CREATE TABLE IF NOT EXISTS `vms`.`visitor_movement_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `visitor_id` INT(10) NULL DEFAULT NULL,
  `location_id` INT(6) NULL DEFAULT NULL,
  `event_type` INT(2) NULL DEFAULT NULL,
  `event_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `visitor_movement_log_visitor_visitor_id` (`visitor_id` ASC) VISIBLE,
  INDEX `visitor_movement_log_security_locations_location_id` (`location_id` ASC) VISIBLE,
  INDEX `fk_visitor_movement_log_event_codes1_idx` (`event_type` ASC) VISIBLE,
  CONSTRAINT `visitor_movement_log_security_locations_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `vms`.`security_locations` (`location_code`),
  CONSTRAINT `visitor_movement_log_visitor_visitor_id`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `vms`.`visitor` (`id`),
  CONSTRAINT `fk_visitor_movement_log_event_codes1`
    FOREIGN KEY (`event_type`)
    REFERENCES `vms`.`event_codes` (`event_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vms`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`admin` ;

CREATE TABLE IF NOT EXISTS `vms`.`admin` (
  `user_id` VARCHAR(40) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `last_logged_in` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`, `password`))
ENGINE = InnoDB;

USE `vms` ;

-- -----------------------------------------------------
-- Placeholder table for view `vms`.`vms_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vms`.`vms_users` (`id` INT, `name` INT, `email` INT, `password` INT, `role_code` INT);

-- -----------------------------------------------------
-- View `vms`.`vms_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vms`.`vms_users`;
DROP VIEW IF EXISTS `vms`.`vms_users` ;
USE `vms`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `vms`.`vms_users` AS
    SELECT 
        `e`.`id` AS `id`,
        `e`.`name` AS `name`,
        `e`.`email` AS `email`,
        `e`.`password` AS `password`,
        `r`.`role_code` AS `role_code`
    FROM
        (`vms`.`employee` `e`
        JOIN `vms`.`employee_role` `r`)
    WHERE
        (`e`.`id` = `r`.`emp_id`) 
    UNION SELECT 
        `s`.`id` AS `id`,
        `s`.`name` AS `name`,
        `s`.`email` AS `email`,
        `s`.`password` AS `password`,
        `r`.`role_code` AS `role_code`
    FROM
        (`vms`.`security` `s`
        JOIN `vms`.`security_role` `r`)
    WHERE
        (`s`.`id` = `r`.`security_id`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
